// Code generated by god. DO NOT EDIT

package meta

var meta = Meta{
	Name:    {{ printf "%q" .Name }} ,
	Version: {{ printf "%q" .Version }} ,
	Author:  {{ printf "%q" .Author }} ,
	Module:  {{ printf "%q" .Module }} ,
}
