//go:build !god

// Code generated by god. 

package meta

var meta = Meta{
	Name:    {{ printf "%q" .Project.Name }},
	Version: {{ printf "%q" .Project.Version }},
	Author:  {{ printf "%q" .Project.Author }},
	Module: {{ printf "%q" .Project.Module }},
}
